[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[project]
name = "ailedeau"
version = "0.1.0"
dependencies = [ "python>=3.12", "scipy>=1.13.0", "pybullet>=3.2.6", "exudyn>=1.9.0", "sympy>=1.13.3", "pydy>=0.7.1", "numpy-stl>=3.1.2", "mujoco>=3.2.5", "mujoco-python-viewer>=0.1.4", "matplotlib>=3.9.2", "networkx>=3.4.2", "pytest>=8.3.4", "toml>=0.10.2", "black>=24.4.0",]

[tool.poetry]
name = "ailedeau"
version = "0.1.0"
description = ""
authors = [ "Baptiste LABAT <baptiste.labat@gmail.com>",]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scipy = "^1.13.0"
pybullet = "^3.2.6"
exudyn = "^1.9.0"
sympy = "^1.13.3"
pydy = "^0.7.1"
numpy-stl = "^3.1.2"
mujoco = "^3.2.5"
mujoco-python-viewer = "^0.1.4"
matplotlib = "^3.9.2"
networkx = "^3.4.2"
pytest = "^8.3.4"
toml = "^0.10.2"

[tool.poetry.group.dev.dependencies]
black = "^24.4.0"
